variables:
  DOCKER_REGISTRY: 729711963438.dkr.ecr.us-east-2.amazonaws.com 
  AWS_DEFAULT_REGION: us-east-2
  APP_NAME: python_etl_image_repo
  DOCKER_HOST: tcp://docker:2375

publish:
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .